apiVersion: apps/v1
kind: Deployment

metadata:
  name: ejm-deployment
  labels:
    app: app-ejemplo

spec:
  selector:
    matchLabels:
      proyecto: app-nginx
  replicas: 1

  template:
    metadata:
      name: nginx
      labels:
        proyecto: app-nginx
    
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: persistent-storage-nginx
              mountPath: /usr/share/nginx/html

      volumes:
        - name: persistent-storage-nginx
          persistentVolumeClaim:
            claimName: pvc-nginx
      
      
